version: "3"
services:
  web:
    image: react-k8s:latest
    ports:
      - "8080:3000"
    environment:
      REACT_APP_MESSAGE: "Hello from docker compose env variable"
#    volumes:
#      - ./config-production.js:/usr/share/nginx/html/config.js