apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-app-deployment
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-demo
          image: react-k8s
          imagePullPolicy: Never #used for getting it to pull local images
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          volumeMounts:
            #override config.js file
            - name: config
              mountPath: "/usr/share/nginx/html/config.js"
              subPath: "config.js"
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: react-app-config
            items:
              - key: "web.properties"
                path: "config.js"