apiVersion: v1
kind: Service
metadata:
  name: react-k8s-env-demo
spec:
  type: NodePort
  selector:
    app: react-k8s-env-demo
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000